### ISSUE TITLE
Slightly confused on which function to be calling on

### ISSUE THREAD

**Issue by JessVuksic** [Gabeele/Blackjack#17]
When allocating memory for a new player im slightly confused on which function I should be calling on.

**Comment by Rachel10011** [comment]
Hi, I have looked at your functions. You can use createPlayer() to create a new player and assign data from the file to that player, then you can use insertNewPlayer() to link those new players to the player list.
Also, in the player module, I used pointer '*' instead of '.' for variables in the struct. Please change it in your module if you don't mind.
